FROM python:3.11-slim

WORKDIR /app

# Prevent Python from writing .pyc files and buffering output
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy FastAPI application code
COPY . .

# Expose FastAPI port
EXPOSE 8080

# Start FastAPI application
CMD ["python", "main.py"]